spring:

#thymeleaf配置
 thymeleaf:
  #关闭thymeleaf缓存
     #关闭thymeleaf缓存
            cache: false


  #数据源连接
 datasource:
  #开启druid后台监控
  username: root
  password: 627627
  #192.168.42.91
  url: jdbc:mysql://localhost:3306/myseckill?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
  driver-class-name: com.mysql.cj.jdbc.Driver
  hikari:
    #最小连接数
    minimum-idle: 5
    #空闲连接的最大存活时间
    idle-timeout: 180000
    #最大连接数
    maximum-pool-size: 10
    #自动提交
    auto-commit: true
    #连接的最大存活时间
    max-lifetime: 180000
    #连接超时时间
    connection-timeout: 30000
    #测试连接是否可用的查询的语句
    connection-test-query: SELECT 1

  #redis配置
 redis:
   host: 192.168.32.128
   port: 6379

#页面静态化，保存在浏览器缓存当中
 web:
   resources:
     add-mappings: true
     cache:
       cachecontrol:
         max-age: 3600s
     chain:
       cache: true
       enabled: true
       compressed: true
     static-locations: classpath:/static/

     #RabbitMQ配置
 rabbitmq:
   host: 192.168.32.128
   username: guest
   password: guest
   #虚拟主机
   virtual-host: /
   port: 5672
   listener:
     simple:
       #消费者最小数量
       concurrency: 10
       #消费者最大数量
       max-concurrency: 10
       #限制消费者每次处理一条消息，处理完再处理下一条
       prefetch: 1
       #启动时默认启动容器
       auto-startup: true
       #被拒绝时重新入队列
       default-requeue-rejected: true
   template:
     retry:
       #发布重试，默认为false
       enabled: true
       #重试的时间，默认为1000ms
       initial-interval: 1000ms
       #最大重试次数
       max-attempts: 3
       #重试最大的时间间隔
       max-interval: 10000ms
       #重试间隔的乘数，比如2.0 第一次等10s,第二次20s,第三次40s
       multiplier: 1.0

#mybatis-plus配置
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.myseckill.seckill.pojo
   #打印执行的sql语句
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
